### ISSUE TITLE
wheel安装httptools出错

### ISSUE THREAD

**Issue by Symb0x76** [summerkirakira/CirnoBot#12]
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\httptools
      copying httptools\_version.py -> build\lib.win-amd64-3.10\httptools
      copying httptools\__init__.py -> build\lib.win-amd64-3.10\httptools
      creating build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\errors.py -> build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\__init__.py -> build\lib.win-amd64-3.10\httptools\parser
      running egg_info
      writing httptools.egg-info\PKG-INFO
      writing dependency_links to httptools.egg-info\dependency_links.txt
      writing requirements to httptools.egg-info\requires.txt
      writing top-level names to httptools.egg-info\top_level.txt
      reading manifest file 'httptools.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info\SOURCES.txt'
      copying httptools\parser\parser.c -> build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\url_parser.c -> build\lib.win-amd64-3.10\httptools\parser
      running build_ext
      building 'httptools.parser.parser' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools, certifi, atlastk, appdirs, altgraph, Werkzeug, websockets, watchgod, waitress, urllib3, ujson, tzdata, typing-extensions, tortoise, tomlkit, SQLAlchemy, soupsieve, socksio, rsa, python-slugify, python-engineio, pypika-tortoise, pyparsing, psutil, prompt-toolkit, Pillow,
 MarkupSafe, itsdangerous, hyperframe, hpack, colorama, charset-normalizer, chardet, bidict, asyncpg, asgiref, anyio, aiofiles, starlette, requests, pytz-deprecation-shim, python-socketio, pydantic, playwright, packaging, loguru, Jinja2, httpcore, h2, databases, click, beautifulsoup4, aiosqlite, uvicorn, tzloca
l, tortoise-orm, httpx, Flask, fastapi, bs4, APScheduler, nonebot2, nonebot-plugin-apscheduler, nonebot-plugin-analysis-bilibili, nonebot-adapter-onebot, nb-cli, nonebot-plugin-what2eat, nonebot-plugin-tarot, nonebot-plugin-gocqhttp
  Attempting uninstall: httptools
    Found existing installation: httptools 0.4.0
    Uninstalling httptools-0.4.0:
      Successfully uninstalled httptools-0.4.0
  Running setup.py install for httptools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for httptools did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\httptools
      copying httptools\_version.py -> build\lib.win-amd64-3.10\httptools
      copying httptools\__init__.py -> build\lib.win-amd64-3.10\httptools
      creating build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\errors.py -> build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\__init__.py -> build\lib.win-amd64-3.10\httptools\parser
      running egg_info
      writing httptools.egg-info\PKG-INFO
      writing dependency_links to httptools.egg-info\dependency_links.txt
      writing requirements to httptools.egg-info\requires.txt
      writing top-level names to httptools.egg-info\top_level.txt
      reading manifest file 'httptools.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info\SOURCES.txt'
      copying httptools\parser\parser.c -> build\lib.win-amd64-3.10\httptools\parser
      copying httptools\parser\url_parser.c -> build\lib.win-amd64-3.10\httptools\parser
      running build_ext
      building 'httptools.parser.parser' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\fxd\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of httptools
  Moving to c:\users\fxd\appdata\local\programs\python\python310\lib\site-packages\httptools-0.4.0.dist-info\
   from C:\Users\FXD\AppData\Local\Programs\Python\Python310\Lib\site-packages\~ttptools-0.4.0.dist-info
  Moving to c:\users\fxd\appdata\local\programs\python\python310\lib\site-packages\httptools\
   from C:\Users\FXD\AppData\Local\Programs\Python\Python310\Lib\site-packages\~ttptools

**Comment by summerkirakira** [comment]
请留意报错提示，httptools在windows上需要Microsoft Visual C++ 14.0支持，可以点击日志中的链接下载Microsoft C++ Build Tools来安装。

**Comment by Symb0x76** [comment]
谢谢，自己已经解决了，忘记新机上没有Build tools了
