### ISSUE TITLE
connect to minecraft server

### ISSUE THREAD

**Issue by ghost** [summerkirakira/CirnoBot#13]
只能连接至_bukkit/spigot/paper_端么，不能用 **rcon** 连接至其他类似**原版端**如 **fabric地毯端**吗

**Comment by summerkirakira** [comment]
CirnoBot**不直接**与Minecraft服务器通信，功能实现依赖上游插件[ServerTap](https://github.com/phybros/servertap), 因此服务端必须能够**兼容插件**才可正常使用。

**Comment by ghost** [comment]
那看来不能安装这个插件的端可以离开了
