### ISSUE TITLE
服务器名称问题

### ISSUE THREAD

**Issue by WM9116** [summerkirakira/CirnoBot#14]
你好，大大
paper 1.18.2 
群聊服务器名称中 .mc 命令   服务器名异常
.mc 命令回复第一行截图：
![QQ截图20220731163341](https://user-images.githubusercontent.com/65065448/182017769-c088ad41-0269-4f9f-8136-452eb0668ef0.png)
请问这个和 paper 有关么
谢谢

**Comment by summerkirakira** [comment]
这边的服务器名称是PlaceholderAPI提供的，需要去占位符那里配置

**Comment by WM9116** [comment]
你好，关于 server 和 player 的已经有了         
玩家名 发送正确的
![_740)}$S2FW~8Z` N7T1CIH](https://user-images.githubusercontent.com/65065448/182025604-88cae1d6-69f2-43a8-8fcc-23fd0a3a3aec.png)
![20220731201228](https://user-images.githubusercontent.com/65065448/182025795-ac26f520-1eda-4008-81fd-bdb0b26987ed.png)
这个报错有影响吗？

**Comment by summerkirakira** [comment]
可以忽略

**Comment by WM9116** [comment]
谢谢
