### ISSUE TITLE
ServerTap已经更新到3.0了

### ISSUE THREAD

**Issue by Xiao-yux** [summerkirakira/CirnoBot#15]

**Comment by summerkirakira** [comment]
看release日志似乎没有什么破坏性升级的地方

**Comment by Xiao-yux** [comment]
那个TLS怎么配置啊
![image](https://user-images.githubusercontent.com/79674967/185530681-e87230d6-8c08-4cd3-9537-74fa8b5c7a84.png)

**Comment by summerkirakira** [comment]
不需要tls的话保留原样就可以了
