### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Xiao-yux** [summerkirakira/CirnoBot#16]
![image](https://user-images.githubusercontent.com/79674967/185538539-89601e1e-a568-42c4-950b-c47f0e1dcbb2.png)
这是什么问题

**Comment by summerkirakira** [comment]
降级servertap版本有效果吗，没有在3.0上测试过

**Comment by Xiao-yux** [comment]
我用的2.0，没敢试3.0怕出问题

**Comment by Xiao-yux** [comment]
我加了793160065这个群能帮我看看怎么办吗
