### ISSUE TITLE
question: address already in use

### ISSUE THREAD

**Issue by madoka-chann** [summerkirakira/CirnoBot#2]
我使用自己下载的gocq端配置了正向http，
在cirnobot上关闭了内置gocq的插件。
同时启动，总有一个是提示被占用的。
![image](https://user-images.githubusercontent.com/57851695/154067745-7c154e6a-1121-4a10-9307-ba6b113886b7.png)

这个不管我改不改都一样，反正端口一样就是会被占用
![image](https://user-images.githubusercontent.com/57851695/154068038-2bbfb80a-f9e2-43f9-a126-866c3a0da179.png)

**Comment by summerkirakira** [comment]
我的建议是使用gocqhttp的反向连接模式
<img width="430" alt="image" src="https://user-images.githubusercontent.com/56951617/154074309-49601233-7079-4b59-ae7f-e11320f1b242.png">
在开放对应端口的同时将127.0.0.1改为你的ip地址
在bot_config.yaml中只需把host改成0.0.0.0即可， 同时也请更改nonebot_plugin_image_server的图片上传url，否则图片词条无法录入

**Comment by madoka-chann** [comment]
了解了，谢谢你。更新文档的时候可以加上这些信息
