### ISSUE TITLE
仓库的plugins是不是不全啊

### ISSUE THREAD

**Issue by QwindF** [summerkirakira/CirnoBot#25]
仓库的plugins是不是不全啊
![image](https://github.com/summerkirakira/CirnoBot/assets/87116340/9cffe145-921d-4281-97dd-6be6bc41e75b)
![image](https://github.com/summerkirakira/CirnoBot/assets/87116340/8ef5ab82-8dfe-4997-97d3-9934cbf6baea)

**Comment by summerkirakira** [comment]
感谢反馈，本项目经过重置，移除了部分与mc无关的插件（但是文档没改
