### ISSUE TITLE
其他插件的配置应该怎么写

### ISSUE THREAD

**Issue by QwindF** [summerkirakira/CirnoBot#26]
我现在以cirnobot为bot框架，添加了许多的插件，一般正常来说是有个env文件的，所有的插件变量都可以在那里面填写
但是ciirnobot却没有，于是我尝试写在`bot_config.yaml`并遵守了`yaml`的格式，但是似乎未读取到。
![image](https://github.com/summerkirakira/CirnoBot/assets/87116340/3dc17183-8088-42c5-a4d8-a84753468f61)

**Comment by summerkirakira** [comment]
确定配置是写在yml文件的根下吗？

**Comment by QwindF** [comment]
我确定

**Comment by QwindF** [comment]
照片里也看得见是顶格

**Comment by summerkirakira** [comment]
在插件中print config也没有么

**Comment by QwindF** [comment]
我在根目录下面补充了个.env文件，然后在里面填写配置，成功了

**Comment by QwindF** [comment]
还有为啥有时候机器人不启动fastapi
这会导致gocq连接不上nonebot2
并且此时mc_fun在刷服务器的消息

**Comment by summerkirakira** [comment]
可能是插件启动顺序的问题，应该重启就能解决

**Comment by QwindF** [comment]
好的
