### ISSUE TITLE
warning: src | 端口被占用，可能原因为图片存储服务器未正常退出，不再重复创建

### ISSUE THREAD

**Issue by madoka-chann** [summerkirakira/CirnoBot#3]
（日志作过处理）

## 我不知道如何配置图片存储服务器的地址：

![image](https://user-images.githubusercontent.com/57851695/154099742-92814795-e1e6-4de3-a870-fd5b5d8cc72f.png)
![image](https://user-images.githubusercontent.com/57851695/154099815-6281f6ef-52b3-4c8f-b3d3-feec622b4ce2.png)
## 上面的的配置是正常的，下面是我改图片存储服务器的地址
![image](https://user-images.githubusercontent.com/57851695/154099680-d43142ec-9d6f-4391-addc-6b5b12d0bae2.png)

启动报错，虽然连接上了gocq反向服务器，但无法执行指令：
```
02-15 23:50:14 [SUCCESS] nonebot | Running NoneBot...
02-15 23:50:14 [INFO] uvicorn | Started server process [344963]
02-15 23:50:14 [INFO] uvicorn | Waiting for application startup.
02-15 23:50:14 [INFO] src | Scheduler Started
02-15 23:50:14 [WARNING] src | 端口被占用，可能原因为图片存储服务器未正常退出，不再重复创建
02-15 23:50:14 [INFO] uvicorn | Application startup complete.
02-15 23:50:14 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:32156 (Press CTRL+C to quit)
02-15 23:50:16 [INFO] uvicorn | ('127.0.0.1', 50386) - "WebSocket /onebot/v11/ws/" [accepted]
02-15 23:50:16 [INFO] nonebot | OneBot V11 | Bot 1024685341 connected
02-15 23:50:16 [INFO] websockets | connection open
```

**Comment by summerkirakira** [comment]
如果是本地的话不需要修改端口哦，留着默认的127.0.0.1:4500就可以了，这个bug是由于nonebot进程退出时未关闭flask子进程导致的，一般完全不会影响使用就没修（ 请问在群聊中发消息终端会有输出么

**Comment by madoka-chann** [comment]
我去测试一下
