### ISSUE TITLE
requirement安装报错

### ISSUE THREAD

**Issue by YipSzeho** [summerkirakira/CirnoBot#9]
error: subprocess-exited-with-error

  × Building wheel for backports.zoneinfo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\backports
      copying src\backports\__init__.py -> build\lib.win-amd64-3.9\backports
      creating build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\_common.py -> build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\_tzpath.py -> build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\_version.py -> build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\_zoneinfo.py -> build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\__init__.py -> build\lib.win-amd64-3.9\backports\zoneinfo
      running egg_info
      writing src\backports.zoneinfo.egg-info\PKG-INFO
      writing dependency_links to src\backports.zoneinfo.egg-info\dependency_links.txt
      writing requirements to src\backports.zoneinfo.egg-info\requires.txt
      writing top-level names to src\backports.zoneinfo.egg-info\top_level.txt
      reading manifest file 'src\backports.zoneinfo.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.png' under directory 'docs'
      warning: no files found matching '*.svg' under directory 'docs'
      no previously-included directories found matching 'docs\_build'
      no previously-included directories found matching 'docs\_output'
      adding license file 'LICENSE'
      adding license file 'licenses/LICENSE_APACHE'
      writing manifest file 'src\backports.zoneinfo.egg-info\SOURCES.txt'
      copying src\backports\zoneinfo\__init__.pyi -> build\lib.win-amd64-3.9\backports\zoneinfo
      copying src\backports\zoneinfo\py.typed -> build\lib.win-amd64-3.9\backports\zoneinfo
      running build_ext
      building 'backports.zoneinfo._czoneinfo' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for backports.zoneinfo
Failed to build backports.zoneinfo
ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects

已安装Microsoft C++ Build Tools，还是有这个错误

**Comment by summerkirakira** [comment]
试试删除requirements.txt中的backports.zoneinfo？这个依赖貌似是新添加的，Windows下缺少测试

**Comment by YipSzeho** [comment]
删了就不报错了
